export { default as Store } from './store/Store';
export {default as Authorization} from './authorization/Authorization'
export {default as ChangePassword} from './сhangePassword/ChangePassword'
export {default as Main} from './main/Main'
export {default as AddItem} from './addItem/AddItem'
export {default as ShowProduct} from './showProduct/ShowProduct'
export {default as Cart} from './cart/Cart'
export {default as Orders} from './orders/Orders'
export {default as ChangeAccount} from './changeAccount/ChangeAccount'
export {default as HelpDesign} from './helpDesign/HelpDesign'
export {default as ChangeDesign} from './changeDesign/ChangeDesign'